# Generated by Django 6.0.5 on 2026-05-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='poster_url',
            field=models.URLField(blank=True, help_text='URL externa del póster (TMDB)', null=True),
        ),
    ]
