# Generated by Django 6.0.5 on 2026-05-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('sala', models.CharField(max_length=50)),
                ('asientos_totales', models.PositiveIntegerField(default=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
