# Generated by Django 6.0.5 on 2026-05-25 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entradas', '0001_initial'),
        ('peliculas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funcion',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='peliculas.pelicula'),
        ),
        migrations.AddField(
            model_name='compra',
            name='funcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='entradas.funcion'),
        ),
    ]
